### ISSUE TITLE
Does Vulkan-Sim plan to support OptiX API?

### ISSUE THREAD

**Issue by SubjectNoi** [ubc-aamodt-group/vulkan-sim#1]

**Comment by tommychouyc** [comment]
Currently we don't have plans to support OptiX. However it might be possible to support the OptiX API in Vulkan-Sim. I think you would need to see what the OptiX API calls disassemble to PTX and route them to execute with the equivalent Vulkan ray tracing API calls that we've simulated in instructions.cc.
