### ISSUE TITLE
getting segmentation fault while running ./RayTracer --scene 6 --height 320 --width 448

### ISSUE THREAD

**Issue by AnkurVerma02** [ubc-aamodt-group/vulkan-sim#10]
the gdb output gives the following
![image](https://github.com/ubc-aamodt-group/vulkan-sim/assets/81774104/05d8f1f4-6a0f-45d3-b41e-e53fe14c3b86)

**Comment by tommychouyc** [comment]
We've just released Vulkan-Sim 2.0.0 and the corresponding mesa repo which removes the Intel driver dependency and can now be run directly on any CPU.
