### ISSUE TITLE
Run./ray tracer-scene 6-height 320-width 448 "Trace dumped" does not appear.

### ISSUE THREAD

**Issue by yigerendegudao** [ubc-aamodt-group/vulkan-sim#12]
Hello, author. When I installed vulkan-sim, the following problems occurred. At this step,/raytracer-scene 6-height 320-width 448 has a problem, and there is no "Trace dumped" in the terminal, which looks just like the situation without the simulator installed. I didn't report any mistakes before doing it. Please take a look at it for me.

<img width="577" alt="1688625225550" src="https://github.com/ubc-aamodt-group/vulkan-sim/assets/104263088/0a339e9a-eb84-46e8-9d25-0e3ebe735dc4">

**Comment by tommychouyc** [comment]
We've just released Vulkan-Sim 2.0.0 and the corresponding mesa repo which removes the Intel driver dependency and can now be run directly on any CPU. There is no longer a need to use traces as you can just run a Vulkan RT application directly.
