### ISSUE TITLE
Generating frames using Vulkan Sim

### ISSUE THREAD

**Issue by MascaChapas27** [ubc-aamodt-group/vulkan-sim#13]
Hello, I read the "Vulkan-Sim: A GPU Architecture Simulator for Ray Tracing" paper and there is a comparison between a scene rendered using a GPU from NVIDIA and Vulkan Sim. I tried running a trace with Vulkan Sim in order to get a render of the scene, but it only outputs stats. Would it be possible to generate an image or a set of frames by running a trace?

**Comment by tommychouyc** [comment]
In the old version of Vulkan-Sim, we dumped out the per-pixel RGB values to a image.binary file and converted that to a png image.

We've just released Vulkan-Sim 2.0.0 and the corresponding mesa repo which removes the Intel driver dependency and can now be run directly on any CPU. In this version, you can set the variable 'writeImageBinary' in vulkan_ray_tracing.cc to true and it should dump out a .ppm file of the frame.
