### ISSUE TITLE
Scene numbers mismatch in Lumibench

### ISSUE THREAD

**Issue by GETINSIDE3** [ubc-aamodt-group/vulkan-sim#19]
Hello,

While running Lumibench, some of the scene numbers (24, 25, 26) are not in match with the README and result in errors.
It seems like simply commenting out the CS:GO scenes from RayTracingInVulkan/src/SceneLists.cpp resolves the issue.
It's minor, but I would greatly appreciate it if you could kindly look at it.

Thank you in advance!

**Comment by lucylufei** [comment]
Thanks for pointing this out! I've updated the scene numbers in the README to match the scene numbers in `SceneLists.cpp`. You can either use the new numbers, or just commenting out the CS:GO scenes works too.

**Comment by GETINSIDE3** [comment]
Sounds great. Thank you!
