### ISSUE TITLE
Error when run RTV6

### ISSUE THREAD

**Issue by liqingy5** [ubc-aamodt-group/vulkan-sim#2]
Hello,
I was following the instructions for building the vulkan-sim and mesa, everything is looking good but when I tried to run the RTV6 to dump the trace, I ran  ./RayTracer and got this X error of failed request.
![image](https://user-images.githubusercontent.com/49260853/193710175-3bb39b4e-c122-4e42-bb75-f48c0b20d260.png)

I was using Ubuntu 20.04 with CUDA 11.7 ,gcc /g++ 9.4.0 and GPU is GTX 1080, I can run the RTV6 without involving vulkan-sim, any idea what might cause this error?

**Comment by tommychouyc** [comment]
Does the computer you're running off have Intel integrated graphics? We currently don't support generating traces with Nvidia GPUs.
Also if you could provide a screenshot of the gdb backtrace, that will be very helpful. Thanks!

**Comment by liqingy5** [comment]
Sorry for the late reply, it's probably the issue of Xorg on my local machine, I will look into that first when I had the chance (quite busy recently). By the way, can Vulkan-sim be installed on other Linux OS like centOS?

**Comment by tommychouyc** [comment]
We haven't tried it out before, but it's probably compatible. Please let us know how it goes!
