### ISSUE TITLE
Question BVH properties

### ISSUE THREAD

**Issue by Yfeng-44** [ubc-aamodt-group/vulkan-sim#29]
Hi!

Regarding the property of the BVH, I noticed that the internal node in BVH has an upper limit of 6 children node at https://github.com/ubc-aamodt-group/vulkan-sim/blob/dc742faa6e5fcfaf415fe51eab71dcf9345388fd/src/cuda-sim/vulkan_acceleration_structure_util.h#L110

Is there any reason for this? or I just simply mis-understand it.

Thanks!
-y

**Comment by tommychouyc** [comment]
That is the compressed layout of the BVH tree that was used in the original Intel Mesa driver. I think the tree is a variation from this [paper](https://www.embree.org/papers/2018-HPG-compressedleafbvh.pdf).

**Comment by Yfeng-44** [comment]
Thank you so much!
