### ISSUE TITLE
Can vulkan-sim be used in NVIDIA RTX2080 Ti ？ 

### ISSUE THREAD

**Issue by WilliamWangPeng** [ubc-aamodt-group/vulkan-sim#3]
Hi dear author,  
    It's an honor to write a letter here, I'm building vulkan-sim on NVIDIA 2080 tI gpu now, I meet the following errors when  executing $ meson  --prefix="${PWD}/lib"  build/ , my python version is over 3.7 which is suggested by meson, but when installing python3.7, the error appears as following:  

![image](https://user-images.githubusercontent.com/51076736/194743986-25137b9f-44e1-4a5e-a015-6831114ca84a.png)

  
![image](https://user-images.githubusercontent.com/51076736/194744306-36b70c1f-9f37-4989-b46e-8f0055783b92.png)

## I wonder if vulkan-sim support NVIDIA gpus ?  

thank you  
best regards  
William

**Comment by mohammadrezasaed** [comment]
We do not support NVIDIA GPUs for creating traces at this point. You would need an intel integrated GPU for that. Running the traces already available would only need a CPU.
The error you're getting is not related to that though. Looks like something is wrong with your installation of meson. Maybe this [link](https://askubuntu.com/questions/1225195/meson-build-error-modulenotfounderror-no-module-named-mesonbuild) can help.
