### ISSUE TITLE
How to add a new scene?

### ISSUE THREAD

**Issue by rodhuega** [ubc-aamodt-group/vulkan-sim#35]
I would like to know what is needed and how to add a new scene to Vulkan-sim. Is there any guide about that?

**Comment by lucylufei** [comment]
You can add new scenes [here](https://github.com/ubc-aamodt-group/RayTracingInVulkan/blob/f5932e7e3a114f22ba0cd6ef58d17887e56f9af6/src/SceneList.cpp#L68) and adding a corresponding function to load the scene. You can use the [BUNNY scene](https://github.com/ubc-aamodt-group/RayTracingInVulkan/blob/f5932e7e3a114f22ba0cd6ef58d17887e56f9af6/src/SceneList.cpp#L337) as a reference, which loads an `.obj` file, transforms it, and sets up the other necessary scene parameters.

**Comment by rodhuega** [comment]
Thanks for the help.
