### ISSUE TITLE
Unsupported Texture Format

### ISSUE THREAD

**Issue by JRPan** [ubc-aamodt-group/vulkan-sim#6]
Hi, 

I'm trying a workload with a texture format not supported yet (VK_FORMAT_R8_UNORM). I'm pretty sure it's very similar to VK_FORMAT_R8G8B8A8_SRGB or VK_FORMAT_R8G8B8A8_UNORM, which are formats supported by the Vulkan-Sim. The difference is VK_FORMAT_R8_UNORM only has one channel (R) instead of RGBA. Can I still use the [intel_tiled_to_linear()](https://github.com/ubc-aamodt-group/mesa-vulkan-sim/blob/main/src/intel/isl/isl_tiled_memcpy.c#L921-L922) to get the texture data? If not, do you have any suggestions on implementing the feature?

Please let me know what you think. Thank you in advance!
JR

**Comment by mohammadrezasaed** [comment]
I believe intel_tiled_to_linear should work and you should change the input arguments for the single color channel.
You might also be able to calculate the offset manually to read the texture directly.

**Comment by JRPan** [comment]
Thank you!
